Profile refresh works
hoshistech/ibloov-mobile-v2 pull request #115
Opened 2023-04-27 09:36 UTC by asogwachiuba

What is in this PR:
Profile refresh works well with good User experience.

2023-04-27 22:28 UTC, divincoder requested changes
Look at comments

2023-04-27 22:28 UTC, divincoder commented on lib/features/places/views/places_detail/place_reviews_view.dart
How does this relate to profile search?

2023-04-27 22:28 UTC, divincoder commented on lib/features/profile/views/my_profile/my_profile_view.dart
> +        child: (viewModel.isBusy || viewModel.isRefreshing)
The Implementation here is wrong, this is not what was asked to be done

2023-04-27 22:28 UTC, divincoder commented on lib/features/profile/views/my_profile/my_profile_view.dart
I don't understand why there are so many changes on this file. I asked you add space to the list bottom, so it can refresh not what you did here.

2023-04-27 22:40 UTC, asogwachiuba commented on lib/features/profile/views/my_profile/my_profile_view.dart
Ohhh I will make that change tomorrow morning. It was not mentioned in the comments. So i assumed it was having a bit of issues.

2023-04-27 22:43 UTC, asogwachiuba commented on lib/features/profile/views/my_profile/my_profile_view.dart
> +        child: (viewModel.isBusy || viewModel.isRefreshing)
But it differentiates from a refresh and an initial loading. Should i still remove it. 
If isBusy is true then it makes the user know its loading 
If isRefreshing is true then it makes the user know it is refreshing.
Should i still delete it?

2023-05-05 14:05 UTC, divincoder commented on lib/features/profile/views/my_profile/my_profile_view.dart
> +        child: (viewModel.isBusy || viewModel.isRefreshing)
You were not supposed to do anything aside add space in this ticket to the tickets list, so allow for space to pull down. All this added is not necessary, I already explained this before you picked this ticket

2023-05-11 18:04 UTC, asogwachiuba commented on lib/features/places/views/places_detail/place_reviews_view.dart
The ticket is not on profile search. Although i think the profile search for event tickets works fine.

2023-05-12 06:08 UTC, closed without merging