Signup prompt is functional
hoshistech/ibloov-mobile-v2 pull request #116
Opened 2023-04-27 15:28 UTC by asogwachiuba

What is in the PR:
Refactored the user types(Guest and Regular)
Added a signup prompt

2023-04-27 22:37 UTC, divincoder requested changes
ReWork this solution

2023-04-27 22:37 UTC, divincoder commented on lib/core/data/enum/signup_user_type.dart
Creating a sqlite table to just track UserType for me is much especially if this table don't have a relationship to another table. 
If you want to save basic thing like this, maybe using FlutterSecureStorage or sharedPref might be more ideal.

2023-04-27 22:37 UTC, divincoder commented on lib/features/events/views/event_detail/event_detail_viewmodel.dart
> +    if (dbService.getCurrentUserType() == SignUpUserType.guest) {
You could have easily just checked the Token if its null. Which will be case for GuestUsers and the logic will be a lot simpler.
In the UserService -> you can call authTokenExist or isLoggedIn.

2023-04-27 22:49 UTC, asogwachiuba commented on lib/core/data/enum/signup_user_type.dart
Yeah thought of using sharedPref as the data is not sensitive. Should i redo it using SharedPref? But i will be more cautious about this next time. Redoing it might take time and although its like an overkill I think its harmless to the codebase.

2023-04-28 06:43 UTC, asogwachiuba commented on lib/features/events/views/event_detail/event_detail_viewmodel.dart
> +    if (dbService.getCurrentUserType() == SignUpUserType.guest) {
Ohh okay. Should i change to checking the Token for identification

2023-05-02 15:08 UTC, divincoder approved these changes

2023-05-02 15:08 UTC, divincoder commented on lib/features/search/view/search_view/search_viewmodel.dart
> +    busy(true);
what is busy()?

Also, what are you trying to achieve here?

2023-05-02 15:21 UTC, divincoder approved these changes

2023-05-02 15:21 UTC, divincoder commented on lib/features/search/view/search_view/search_viewmodel.dart
> +    busy(true);
I will merge this. But come back and answer and resolve it

2023-05-02 15:21 UTC, merged