RefferrdBy added
hoshistech/ibloov-mobile-v2 pull request #122
Opened 2023-05-04 08:23 UTC by asogwachiuba

What is the PR:
RefferredBy added for email signup, google signup and apple signup

2023-05-05 14:32 UTC, divincoder requested changes

2023-05-05 14:32 UTC, divincoder commented on lib/core/services/signup/signup_service.dart
> +      final request = (referredBy == null || referredBy.isEmpty)
This is not necessary, null is fine for referredBy.
No?

2023-05-05 14:32 UTC, divincoder commented on lib/core/services/signup/signup_service.dart
> +      final request = (referredBy == null || referredBy.isEmpty)
Please refer to the comment above

2023-05-05 14:32 UTC, divincoder commented on lib/core/services/signup/signup_service.dart
> +      final request = (referredBy == null || referredBy.isEmpty)
refer to the comment above

2023-05-11 18:09 UTC, asogwachiuba commented on lib/core/services/signup/signup_service.dart
> +      final request = (referredBy == null || referredBy.isEmpty)
I did this cause there is no need having a referredBy param if its null. Like if its not useful why pass it as an api param.

2023-05-11 19:08 UTC, divincoder commented on lib/core/services/signup/signup_service.dart
> +      final request = (referredBy == null || referredBy.isEmpty)
There is no problem passing null to an API param. Was there an issue with the API when you passed null? 
when you call the endpoint with that value not existent, it is still null being passed implicitly.

2023-05-11 19:09 UTC, divincoder commented on lib/core/services/signup/signup_service.dart
> +      final request = (referredBy == null || referredBy.isEmpty)
Just making sure the code is elegant. Currently, I don't like those checks like that

2023-05-11 20:41 UTC, asogwachiuba commented on lib/core/services/signup/signup_service.dart
> +      final request = (referredBy == null || referredBy.isEmpty)
Okay. I was on the road back home, thats why it took me time to reply. 
What you said makes sense. not passing it implicitly means the api interprets the value of the param as null. I will make the update this night.

2023-05-11 22:15 UTC, asogwachiuba commented on lib/core/services/signup/signup_service.dart
> +      final request = (referredBy == null || referredBy.isEmpty)
The update has been done.

2023-05-12 09:05 UTC, divincoder approved these changes

2023-05-12 09:05 UTC, merged