Space added to profile for refreshing
hoshistech/ibloov-mobile-v2 pull request #127
Opened 2023-05-12 06:08 UTC by asogwachiuba

What is in the PR: 
Space added to the bottom of My Tickets section

2023-05-12 09:14 UTC, divincoder requested changes

2023-05-12 09:14 UTC, divincoder commented on lib/features/profile/views/my_profile/my_profile_view.dart
> +                                  height: 20,
make this 80 or 100

2023-05-12 16:17 UTC, asogwachiuba commented on lib/features/profile/views/my_profile/my_profile_view.dart
> +                                  height: 20,
Okay.

2023-05-12 17:56 UTC, asogwachiuba commented on lib/features/profile/views/my_profile/my_profile_view.dart
> +                                  height: 20,
Done

2023-05-14 14:14 UTC, divincoder approved these changes

2023-05-14 14:14 UTC, merged