2209 guest user
hoshistech/ibloov-mobile-v2 pull request #139
Opened 2023-05-21 20:51 UTC by asogwachiuba

Whats is in this PR:
Added a guest signup tracker service
Updated guest userflow after signing up
User's actions leading to signing up is done after signing up
User is carried back to the screen he/she was before signing up

Its an internal update.

2023-05-24 10:05 UTC, divincoder requested changes

2023-05-24 10:05 UTC, divincoder commented on lib/features/events/views/event_detail/event_details_view.dart
> +                                        ? Navigator.push(
Why are you using this type of Navigator with context. Why are you no using NavigationService. Also, why do you need to be reminded to used the correct stuffs at this point?

2023-05-24 10:05 UTC, divincoder commented on lib/features/events/views/event_detail/event_details_view.dart
> +                                        : Navigator.pop(context);
Please remove all this Navigator stuff

2023-05-24 10:05 UTC, divincoder commented on lib/features/events/views/explore/item/event_item_view_model.dart
> +    final pref = await SharedPreferences.getInstance();
I would expect you to create a SharedPrefService if doesn't exist instead of doing this

2023-05-24 10:36 UTC, asogwachiuba commented on lib/features/events/views/explore/item/event_item_view_model.dart
> +    final pref = await SharedPreferences.getInstance();
Okay will implement this asap.

2023-05-24 11:23 UTC, asogwachiuba commented on lib/core/app/app.dart
> +    classType: GuestUserTracker,
Okay, sure.

2023-05-24 11:24 UTC, asogwachiuba commented on lib/features/events/views/event_detail/event_details_view.dart
> +                                        ? Navigator.push(
I will strictly use navigation service from now on.

2023-05-24 11:24 UTC, asogwachiuba commented on lib/features/events/views/event_detail/event_details_view.dart
> +                                        : Navigator.pop(context);
Okay sure i will

2023-05-24 11:34 UTC, asogwachiuba commented on lib/features/events/views/explore/item/event_item_view_model.dart
> +    final pref = await SharedPreferences.getInstance();
It exisits already. So i will just use it

2023-05-25 10:35 UTC, divincoder approved these changes

2023-05-25 10:35 UTC, merged