Button text 'But Tickets' in event details updated
hoshistech/ibloov-mobile-v2 pull request #158
Opened 2023-06-02 14:09 UTC by asogwachiuba

Buy ticket button name in event details changes to 'Get Tickets'
Screenshots:

![Simulator Screen Shot - iPhone SE (3rd generation) - 2023-06-02 at 15 07 04](https://github.com/hoshistech/ibloov-mobile-v2/assets/77053305/ee2b8bf4-2155-40a5-bba2-61235d3680e7)

2023-06-02 14:38 UTC, divincoder requested changes

2023-06-02 14:38 UTC, divincoder commented on lib/features/events/views/event_detail/widgets/buy_tickets.dart
> +                          text: "Get Ticket",
I don't understand this change? why?

2023-06-02 21:41 UTC, asogwachiuba commented on lib/features/events/views/event_detail/widgets/buy_tickets.dart
> +                          text: "Get Ticket",
It was made for generalization. PM wants a one name to capture both scenarios

2023-06-02 21:43 UTC, asogwachiuba commented on lib/features/events/views/event_detail/widgets/buy_tickets.dart
> +                          text: "Get Ticket",
This is a link to the ticket addressing this: 
https://hoshis-tech.atlassian.net/jira/software/projects/IWORG/boards/2?selectedIssue=IWORG-2406

2023-06-05 08:08 UTC, divincoder approved these changes

2023-06-05 08:08 UTC, merged